"""Shared helpers for plugin/install.py, status.py and uninstall.py.

Pure builders (runtime config, manifest) are kept separate from the calls that
touch the tenant or the SailPoint CLI, so the tests can check every payload
without a tenant.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

PLUGIN_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(PLUGIN_DIR.parent / "core"))

from bulkaccess import config as config_mod  # noqa: E402
from bulkaccess import definitions  # noqa: E402
from bulkaccess.config import Config  # noqa: E402
from bulkaccess.tenant import Tenant, TenantError, load_env_file  # noqa: E402

WORKFLOWS = "/v2025/workflows"
RUNTIME_CONFIG = Path("public") / "bulk-access.config.json"
MANIFEST = Path("sp-ui-plugin.json")
BUILD_OUT_DIR = "./dist/bulk-access-request-plugin/browser"

__all__ = ["Config", "Tenant", "TenantError", "config_mod", "definitions"]


# ─────────────────────────────────────────────────────────── pure builders ──
def runtime_config(cfg: Config, workflow_id: str | None = None) -> dict[str, Any]:
    """public/bulk-access.config.json: everything the page needs from the tenant config."""
    return {
        "_comment": "Generated by plugin/install.py from the tenant config. Re-run install.py instead of editing.",
        "prefix": cfg.prefix,
        "mode": cfg.mode,
        "workflowName": cfg.plugin_workflow_name,
        "workflowId": workflow_id,
        "incPattern": cfg.inc_pattern,
        "incMessage": cfg.inc_message,
        "incExample": cfg.inc_example,
        # null = no limit; bigger lists go out as several approvals of `partSize` (the loop limit).
        "peopleMax": cfg.plugin_people_max,
        "partSize": cfg.part_size,
        "itemsMax": cfg.catalog_max_items,
        "catalogTypes": list(cfg.catalog_types),
        "nameStartsWith": cfg.catalog_name_starts_with,
        "launcherName": cfg.launcher_name,
        "temporary": {
            "enabled": cfg.temporary_enabled,
            "allow": list(cfg.temporary_allow),
            "units": list(cfg.temporary_units),
            "maxDays": cfg.temporary_max_days,
        },
    }


def manifest(cfg: Config) -> dict[str, Any]:
    """sp-ui-plugin.json for this tenant's alias and display name."""
    return {
        "version": 1,
        "manifest": {
            "alias": cfg.plugin_alias,
            "name": {"en": cfg.plugin_display_name},
            "description": {"en": "Request access for several people at once: one approver for the whole request, "
                                  "and a ServiceNow INC number on every item. Requires ORG_ADMIN (it starts a workflow "
                                  "through the workflow test endpoint)."},
            "apiScopes": ["sp:scopes:all"],
            "permissionPolicy": {},
            "iframeAllow": {},
            "contentSecurityPolicies": {},
            "slots": [{"slotId": "full-page"}],
            "state": "ENABLED",
        },
        "build": {"outDir": BUILD_OUT_DIR, "port": 4200},
    }


def plugin_workflow(cfg: Config, owner_id: str, owner_name: str | None) -> dict[str, Any]:
    """The plugin workflow body, always DISABLED (it only runs through the test endpoint)."""
    body = definitions.bulk_workflow(cfg, variant="plugin", owner_id=owner_id, owner_name=owner_name)
    body["enabled"] = False
    # SailPoint's validator rejects failure end steps without failureName/description
    # (error e300). Newer core versions set them; fill them in for older ones.
    for step in body["definition"]["steps"].values():
        if step.get("type") == "failure":
            step.setdefault("failureName", "Bulk request rejected")
            step.setdefault("description", "Stopped before approval: the approver was the requester, "
                                           "or the INC number was invalid.")
    _loop_sees_workflow_state(body)
    return body


def _loop_sees_workflow_state(body: dict[str, Any]) -> None:
    """Steps inside a SailPoint loop only see `$.loop.*`. Templates such as
    "{{$.trigger.inc}}" in Manage Access's comment stay literal unless the loop's
    context is the whole workflow state ("$") and the paths go through it.
    Verified live; a no-op once core/definitions.py builds the loop this way."""
    loop = body["definition"]["steps"].get("Request Access")
    if not loop or loop["attributes"].get("context.$") == "$":
        return
    attrs = loop["attributes"]
    manage = attrs["steps"]["Manage Access"]["attributes"]
    items_path = attrs["context.$"]                    # e.g. "$.trigger.items"
    attrs["context.$"] = "$"
    manage["requestedItems.$"] = "$.loop.context" + items_path[1:]
    manage["comments"] = manage["comments"].replace("{{$.", "{{$.loop.context.")


def owned_by_us(cfg: Config, name: str | None) -> bool:
    """Only touch objects whose name carries our prefix and the plugin suffix."""
    return bool(name) and name == cfg.plugin_workflow_name and name.startswith(cfg.prefix + " ")


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(data, indent=2) + "\n"
    if path.exists():
        # Rewrite in place so the file keeps its permissions (the folder is shared with a Mac).
        with open(path, "r+", encoding="utf-8") as fh:
            fh.seek(0)
            fh.write(text)
            fh.truncate()
    else:
        path.write_text(text, encoding="utf-8")
        os.chmod(path, 0o644)


# ──────────────────────────────────────────────────────────────── tenant ──
def whoami(tenant: Tenant) -> dict[str, Any]:
    """The PAT's identity. Calls /v2025/identities directly (older core used a v3 path that 404s)."""
    claims = json.loads(_b64url(tenant.token().split(".")[1]))
    identity_id = claims.get("identity_id")
    if not identity_id:
        raise TenantError(0, "The PAT has no identity_id claim; use a personal access token, not a client app.")
    return tenant.call("GET", f"/v2025/identities/{identity_id}")


def find_workflow(tenant: Tenant, name: str) -> dict[str, Any] | None:
    return next((w for w in tenant.call("GET", f"{WORKFLOWS}?limit=250") or [] if w.get("name") == name), None)


def _b64url(segment: str) -> str:
    import base64
    return base64.urlsafe_b64decode(segment + "=" * (-len(segment) % 4)).decode()


# ─────────────────────────────────────────────────────────── SailPoint CLI ──
def sail_env(cfg: Config) -> dict[str, str]:
    """Environment for `sail`: the PAT from the config's envFile, passed as variables (never as arguments)."""
    load_env_file(cfg.env_file)
    env = dict(os.environ)
    missing = [k for k in ("SAIL_BASE_URL", "SAIL_CLIENT_ID", "SAIL_CLIENT_SECRET") if not env.get(k)]
    if missing:
        raise TenantError(0, "Missing credentials for the SailPoint CLI: " + ", ".join(missing))
    return env


def sail(cfg: Config, args: list[str], workdir: Path, *, check: bool = True) -> subprocess.CompletedProcess[str]:
    """Run `sail <args>` in `workdir`. stdin is /dev/null: some commands prompt and would hang."""
    exe = os.environ.get("SAIL") or shutil.which("sail") or str(Path.home() / ".local/bin/sail")
    proc = subprocess.run([exe, *args], cwd=workdir, env=sail_env(cfg), stdin=subprocess.DEVNULL,
                          capture_output=True, text=True)
    if check and proc.returncode != 0:
        raise TenantError(proc.returncode, f"sail {' '.join(args)} failed:\n{proc.stdout}{proc.stderr}")
    return proc


def find_plugin(cfg: Config, workdir: Path) -> dict[str, Any] | None:
    proc = sail(cfg, ["ui-plugins", "list", "--json"], workdir)
    out = proc.stdout.strip()
    start = out.find("[")
    rows = json.loads(out[start:]) if start >= 0 else []
    hit = next((p for p in rows if p.get("alias") == cfg.plugin_alias), None)
    # The CLI's JSON calls the ID `pluginInstanceId`; the scripts use `id`.
    return {**hit, "id": hit.get("pluginInstanceId") or hit.get("id")} if hit else None
